[tool.poetry]
name = "toml-validator"
version = "0.1.0"
description = "Simple TOML file validator using Python."
authors = ["Thiago Carvalho D'Ávila <thiagocavila@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/staticdev/toml-validator"

[tool.poetry.dependencies]
python = "^3.7"
tomlkit = "^0.5.9"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
coverage = {extras = ["toml"], version = "^5.0.3"}
pytest-cov = "^2.8.1"

[tool.poetry.scripts]
toml-validator = "toml_validator.console:main"
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.coverage.paths]
source = ["src", "*/site-packages"] # configure source tree layout

[tool.coverage.run]
branch = true # enable branch analysis
source = ["toml_validator"] # configure package name

[tool.coverage.report]
show_missing = true # display line number of missing coverage
